### ISSUE TITLE
code block 的代码会被注释掉

### ISSUE THREAD

**Issue by togo13duke** [xrr2016/hexo-theme-cold-stone#7]
只要有comment out的以下的代码都会被注释掉

* Local环境的Code Block

![image](https://user-images.githubusercontent.com/23131516/66285248-cb378600-e906-11e9-9d30-ffb330e164b5.png)

* Serve时的Code Block
![image](https://user-images.githubusercontent.com/23131516/66285338-1ea9d400-e907-11e9-8a7c-11c952d3dc73.png)

**Comment by xrr2016** [comment]
> 只要有comment out的以下的代码都会被注释掉
> 
> * Local环境的Code Block
> 
> ![image](https://user-images.githubusercontent.com/23131516/66285248-cb378600-e906-11e9-9d30-ffb330e164b5.png)
> 
> * Serve时的Code Block
>   ![image](https://user-images.githubusercontent.com/23131516/66285338-1ea9d400-e907-11e9-8a7c-11c952d3dc73.png)

我发现是启用了 hexo 自带的代码高亮后又用 hljs 高亮代码块造成的问题，hexo 自带的代码高亮不起作用，只能关闭 hexo 自带的代码高亮，然后自己使用 hljs 设置高亮了

```yml
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: false
```

**Comment by togo13duke** [comment]
改了yml反倒代码高亮不起作用了。

![image](https://user-images.githubusercontent.com/23131516/66369265-a874a280-e9d6-11e9-9ff7-03ec55887f3d.png)

是不是我少了什么配置 ??

_config.yml

```yml
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: false
```

package.json

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-deployer-git": "^2.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-wordcount": "^6.0.1"
  }
}
```
